# Encoding techniques

### Label Encoding

In [1]:
import pandas as pd

df = pd.DataFrame({

    'Employee_ID':[101,102,103,104,105,106,107,108,109,110],

    'Gender':[
        'Male','Female','Male','Female','Male',
        'Female','Male','Female','Male','Female'
    ],

    'Department':[
        'HR','IT','Finance','IT','Marketing',
        'HR','Finance','Marketing','IT','HR'
    ],

    'Education_Level':[
        'High School',
        'Bachelors',
        'Masters',
        'PhD',
        'Bachelors',
        'Masters',
        'PhD',
        'High School',
        'Bachelors',
        'Masters'
    ],

    'City':[
        'Mumbai',
        'Delhi',
        'Pune',
        'Mumbai',
        'Bangalore',
        'Delhi',
        'Chennai',
        'Pune',
        'Mumbai',
        'Bangalore'
    ],

    'Performance':[
        'Good',
        'Excellent',
        'Average',
        'Excellent',
        'Good',
        'Average',
        'Excellent',
        'Good',
        'Excellent',
        'Average'
    ]
})

df

   Employee_ID  Gender Department Education_Level       City Performance
0          101    Male         HR     High School     Mumbai        Good
1          102  Female         IT       Bachelors      Delhi   Excellent
2          103    Male    Finance         Masters       Pune     Average
3          104  Female         IT             PhD     Mumbai   Excellent
4          105    Male  Marketing       Bachelors  Bangalore        Good
5          106  Female         HR         Masters      Delhi     Average
6          107    Male    Finance             PhD    Chennai   Excellent
7          108  Female  Marketing     High School       Pune        Good
8          109    Male         IT       Bachelors     Mumbai   Excellent
9          110  Female         HR         Masters  Bangalore     Average

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
LE = LabelEncoder()

In [4]:
df["Gender"].value_counts()

Gender
Male      5
Female    5
Name: count, dtype: int64

In [5]:
df["Gender"] = LE.fit_transform(df["Gender"]) #used when there is a two unique values in a column

In [6]:
df["Gender"][:3]

0    1
1    0
2    1
Name: Gender, dtype: int64

In [7]:
df["Gender"].value_counts() #used to count the value

Gender
1    5
0    5
Name: count, dtype: int64

In [76]:
#df["Department"] = LE.fit_transform(df["Department"])

In [77]:
#df["Department"][:3]

### OneHotEncoding

In [8]:
df["Department"].value_counts()

Department
HR           3
IT           3
Finance      2
Marketing    2
Name: count, dtype: int64

In [9]:
pd.get_dummies(df["Department"],drop_first=True) #Drop_first=True is used to reduce the complexity and delete 1st labeled coulmn

      HR     IT  Marketing
0   True  False      False
1  False   True      False
2  False  False      False
3  False   True      False
4  False  False       True
5   True  False      False
6  False  False      False
7  False  False       True
8  False   True      False
9   True  False      False

### Ordinal Encoding

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
order = OrdinalEncoder()

In [12]:
df["Performance"] = order.fit_transform(df[["Performance"]]) # this gives default values to the column values

In [13]:
df["Performance"]

0    2.0
1    1.0
2    0.0
3    1.0
4    2.0
5    0.0
6    1.0
7    2.0
8    1.0
9    0.0
Name: Performance, dtype: float64

In [14]:
# to give specific encoded values to the column
oe = OrdinalEncoder(
    categories = [[        
        'Good',
        'Average',
        'Excellent'
    ]]
)
df["Performance"] = oe.fit_transform(df[["Performance"]])
print(df)

ValueError: could not convert string to float: 'Good'

In [16]:
df["Education_Level"].value_counts()

Education_Level
Bachelors      3
Masters        3
High School    2
PhD            2
Name: count, dtype: int64

In [17]:
df["Education_Level"] = order.fit_transform(df[["Education_Level"]])

In [18]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[[
        'High School',
        'Bachelors',
        'Masters',
        'PhD'
    ]]
)

df["Education_Level"] = oe.fit_transform(df[["Education_Level"]])

df.head()

ValueError: could not convert string to float: 'High School'

In [92]:
df["City"].value_counts()

City
Mumbai       3
Delhi        2
Pune         2
Bangalore    2
Chennai      1
Name: count, dtype: int64

In [93]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[[
        'Bangalore',
        'Chennai',
        'Delhi',
        'Mumbai',
        'Pune'
    ]]
)

df["City"] = oe.fit_transform(df[["City"]])

print(df.head())

   Employee_ID  Gender Department  Education_Level  City Performance
0          101    Male         HR              0.0   3.0        Good
1          102  Female         IT              1.0   2.0   Excellent
2          103    Male    Finance              2.0   4.0     Average
3          104  Female         IT              3.0   3.0   Excellent
4          105    Male  Marketing              1.0   0.0        Good

In [94]:
df["City"].value_counts()

City
3.0    3
2.0    2
4.0    2
0.0    2
1.0    1
Name: count, dtype: int64

In [101]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[[
        'HR',
        'IT',
        'Finance',
        'Marketing',
    ]]
)

df["Department"] = oe.fit_transform(df[["Department"]])

print(df.head())

   Employee_ID  Gender  Department Education_Level       City Performance
0          101    Male         0.0     High School     Mumbai        Good
1          102  Female         1.0       Bachelors      Delhi   Excellent
2          103    Male         2.0         Masters       Pune     Average
3          104  Female         1.0             PhD     Mumbai   Excellent
4          105    Male         3.0       Bachelors  Bangalore        Good

In [102]:
df["Department"] = df["Department"].replace({"HR":0,"IT":1,"Finance":2,"Marketing":3})

In [ ]:
df["Department"]