In [3]:
import pandas as pd

In [20]:
df = pd.read_csv('laptop_price.csv', encoding='Windows-1252')

In [21]:
df

      laptop_ID Company  ...  Weight Price_euros
0             1   Apple  ...  1.37kg     1339.69
1             2   Apple  ...  1.34kg      898.94
2             3      HP  ...  1.86kg      575.00
3             4   Apple  ...  1.83kg     2537.45
4             5   Apple  ...  1.37kg     1803.60
...         ...     ...  ...     ...         ...
1298       1316  Lenovo  ...   1.8kg      638.00
1299       1317  Lenovo  ...   1.3kg     1499.00
1300       1318  Lenovo  ...   1.5kg      229.00
1301       1319      HP  ...  2.19kg      764.00
1302       1320    Asus  ...   2.2kg      369.00

[1303 rows x 13 columns]

# Filter DF based on Condition

In [26]:
df['Company'] == 'Apple'

0        True
1        True
2       False
3        True
4        True
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Name: Company, Length: 1303, dtype: bool

In [27]:
df[df['Company'] == 'Apple']

      laptop_ID Company      Product  ...     OpSys   Weight Price_euros
0             1   Apple  MacBook Pro  ...     macOS   1.37kg     1339.69
1             2   Apple  Macbook Air  ...     macOS   1.34kg      898.94
3             4   Apple  MacBook Pro  ...     macOS   1.83kg     2537.45
4             5   Apple  MacBook Pro  ...     macOS   1.37kg     1803.60
6             7   Apple  MacBook Pro  ...  Mac OS X   2.04kg     2139.97
7             8   Apple  Macbook Air  ...     macOS   1.34kg     1158.70
12           13   Apple  MacBook Pro  ...     macOS   1.83kg     2439.97
14           15   Apple  MacBook 12"  ...     macOS   0.92kg     1262.40
15           16   Apple  MacBook Pro  ...     macOS   1.37kg     1518.55
17           18   Apple  MacBook Pro  ...     macOS   1.83kg     2858.00
26           27   Apple  MacBook Air  ...  Mac OS X   1.35kg     1099.00
34           35   Apple  MacBook Air  ...  Mac OS X   1.35kg      998.00
45           46   Apple  MacBook Pro  ...     macOS   1.37kg     1419.00
81           83   Apple  MacBook 12"  ...     macOS   0.92kg     1510.00
249         254   Apple  MacBook Pro  ...     macOS   1.37kg     2040.00
270         275   Apple  MacBook Pro  ...     macOS   1.37kg     1958.90
794         803   Apple  MacBook 12"  ...  Mac OS X  0.920kg     1165.00
1069       1084   Apple  MacBook 12"  ...  Mac OS X  0.920kg     1300.00
1193       1211   Apple  MacBook 12"  ...  Mac OS X  0.920kg     1163.00
1210       1228   Apple  MacBook 12"  ...  Mac OS X  0.920kg     1279.00
1234       1252   Apple  MacBook Air  ...  Mac OS X   1.08kg      959.00

[21 rows x 13 columns]

In [32]:
df[df['Company'] == 'Apple'].value_counts('Company')

Company
Apple    21
Name: count, dtype: int64

In [36]:
# Find which row not have "HP" in a Company column
df[df['Company'] != 'HP'].value_counts('Company')

Company
Lenovo       297
Dell         297
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [43]:
# Find laptops over 2000 euros
df[df['Price_euros'] > 2000.0]

      laptop_ID Company        Product  ...       OpSys  Weight Price_euros
3             4   Apple    MacBook Pro  ...       macOS  1.83kg     2537.45
6             7   Apple    MacBook Pro  ...    Mac OS X  2.04kg     2139.97
12           13   Apple    MacBook Pro  ...       macOS  1.83kg     2439.97
17           18   Apple    MacBook Pro  ...       macOS  1.83kg     2858.00
58           59     MSI     GS73VR 7RG  ...  Windows 10  2.43kg     2449.00
...         ...     ...            ...  ...         ...     ...         ...
1203       1221    Dell         XPS 13  ...  Windows 10   1.2kg     2680.00
1209       1227    Asus      Rog Strix  ...  Windows 10   2.2kg     2449.00
1231       1249   Razer      Blade Pro  ...  Windows 10  1.95kg     3499.00
1236       1254      HP  EliteBook 840  ...   Windows 7  1.54kg     2198.19
1247       1265    Asus    Rog GL502VS  ...  Windows 10  2.34kg     2325.00

[137 rows x 13 columns]

# Create Column based on Condition

In [44]:
import numpy as np

In [46]:
tier = np.where(df['Price_euros'] > 2000.0 , "Expensive" , "Cheap")
tier

array(['Cheap', 'Cheap', 'Cheap', ..., 'Cheap', 'Cheap', 'Cheap'],
      shape=(1303,), dtype='<U9')

In [48]:
df['Product_tier'] = tier
df.head()

   laptop_ID Company      Product  ...  Weight  Price_euros Product_tier
0          1   Apple  MacBook Pro  ...  1.37kg      1339.69        Cheap
1          2   Apple  Macbook Air  ...  1.34kg       898.94        Cheap
2          3      HP       250 G6  ...  1.86kg       575.00        Cheap
3          4   Apple  MacBook Pro  ...  1.83kg      2537.45    Expensive
4          5   Apple  MacBook Pro  ...  1.37kg      1803.60        Cheap

[5 rows x 14 columns]

In [52]:
df[df['Product_tier'] == "Cheap"].value_counts("Product_tier")

Product_tier
Cheap    1166
Name: count, dtype: int64

# Exercise

In [61]:
# based on inches series , divide small and big screen laptops (> 15 big else small)
df[df['Inches'] > 15.0]

      laptop_ID Company  ... Price_euros Product_tier
2             3      HP  ...      575.00        Cheap
3             4   Apple  ...     2537.45    Expensive
5             6    Acer  ...      400.00        Cheap
6             7   Apple  ...     2139.97    Expensive
10           11      HP  ...      393.90        Cheap
...         ...     ...  ...         ...          ...
1294       1312      HP  ...      549.99        Cheap
1295       1313    Dell  ...      805.99        Cheap
1297       1315    Asus  ...      720.32        Cheap
1301       1319      HP  ...      764.00        Cheap
1302       1320    Asus  ...      369.00        Cheap

[835 rows x 14 columns]

In [62]:
size = np.where(df['Inches'] > 15.0 , "Big" , "Small")
size

array(['Small', 'Small', 'Big', ..., 'Small', 'Big', 'Big'],
      shape=(1303,), dtype='<U5')

In [71]:
df.insert(4, 'Screen_Size' , size)
df.head()

   laptop_ID Company      Product  ...  Weight Price_euros  Product_tier
0          1   Apple  MacBook Pro  ...  1.37kg     1339.69         Cheap
1          2   Apple  Macbook Air  ...  1.34kg      898.94         Cheap
2          3      HP       250 G6  ...  1.86kg      575.00         Cheap
3          4   Apple  MacBook Pro  ...  1.83kg     2537.45     Expensive
4          5   Apple  MacBook Pro  ...  1.37kg     1803.60         Cheap

[5 rows x 15 columns]

In [72]:
df.value_counts('Screen_Size')

Screen_Size
Big      835
Small    468
Name: count, dtype: int64

# Filter based on multiple condition

In [77]:
# find apple laptops that costs more than 2000
df[(df['Company'] == 'Apple') & (df['Price_euros'] > 2000.0)]

     laptop_ID Company      Product  ...  Weight Price_euros  Product_tier
3            4   Apple  MacBook Pro  ...  1.83kg     2537.45     Expensive
6            7   Apple  MacBook Pro  ...  2.04kg     2139.97     Expensive
12          13   Apple  MacBook Pro  ...  1.83kg     2439.97     Expensive
17          18   Apple  MacBook Pro  ...  1.83kg     2858.00     Expensive
249        254   Apple  MacBook Pro  ...  1.37kg     2040.00     Expensive

[5 rows x 15 columns]

In [79]:
# find laptops whic are apple or dells
df[(df['Company'] == 'Apple') | (df['Company'] == 'Dell')]

      laptop_ID Company        Product  ...  Weight Price_euros  Product_tier
0             1   Apple    MacBook Pro  ...  1.37kg     1339.69         Cheap
1             2   Apple    Macbook Air  ...  1.34kg      898.94         Cheap
3             4   Apple    MacBook Pro  ...  1.83kg     2537.45     Expensive
4             5   Apple    MacBook Pro  ...  1.37kg     1803.60         Cheap
6             7   Apple    MacBook Pro  ...  2.04kg     2139.97     Expensive
...         ...     ...            ...  ...     ...         ...           ...
1278       1296    Dell  Inspiron 3552  ...  2.20kg      379.00         Cheap
1281       1299    Dell  Inspiron 3567  ...   2.3kg      805.99         Cheap
1290       1308    Dell  Inspiron 3567  ...   2.3kg      459.00         Cheap
1292       1310    Dell  Inspiron 3552  ...  2.20kg      379.00         Cheap
1295       1313    Dell  Inspiron 3567  ...   2.3kg      805.99         Cheap

[318 rows x 15 columns]

In [87]:
# find laptops of apple or dell that cost over 2000
df[((df['Company'] == 'Apple') | (df['Company'] == 'Dell')) & (df['Price_euros'] > 2000.0)]

      laptop_ID Company          Product  ...  Weight Price_euros  Product_tier
3             4   Apple      MacBook Pro  ...  1.83kg     2537.45     Expensive
6             7   Apple      MacBook Pro  ...  2.04kg     2139.97     Expensive
12           13   Apple      MacBook Pro  ...  1.83kg     2439.97     Expensive
17           18   Apple      MacBook Pro  ...  1.83kg     2858.00     Expensive
186         190    Dell           XPS 15  ...  2.06kg     2397.00     Expensive
204         208    Dell   Precision 7520  ...   2.8kg     3055.00     Expensive
224         229    Dell     Alienware 17  ...  4.42kg     2456.34     Expensive
249         254   Apple      MacBook Pro  ...  1.37kg     2040.00     Expensive
297         302    Dell   Precision 7720  ...  3.42kg     2884.86     Expensive
311         316    Dell           XPS 13  ...  1.21kg     2499.00     Expensive
329         335    Dell           XPS 15  ...  2.06kg     2639.00     Expensive
350         356    Dell           XPS 15  ...  2.06kg     2027.42     Expensive
388         394    Dell   Precision 5520  ...     2kg     2135.00     Expensive
398         405    Dell  Precision M5520  ...  1.78kg     2712.00     Expensive
424         431    Dell     Alienware 17  ...  4.42kg     2799.00     Expensive
456         463    Dell     Alienware 17  ...  4.42kg     2046.00     Expensive
476         483    Dell  Precision M5520  ...  1.78kg     2408.00     Expensive
486         493    Dell   Precision 3520  ...  2.17kg     2338.00     Expensive
530         537    Dell     Alienware 17  ...  4.42kg     3012.77     Expensive
552         559    Dell     Alienware 17  ...  4.42kg     2699.00     Expensive
639         647    Dell           XPS 15  ...  2.06kg     2399.00     Expensive
659         667    Dell     Alienware 17  ...  4.42kg     3147.37     Expensive
682         690    Dell     Alienware 15  ...  3.21kg     2051.00     Expensive
685         693    Dell     Alienware 15  ...  3.49kg     2813.75     Expensive
723         731    Dell     Alienware 17  ...  4.36kg     3659.40     Expensive
758         767    Dell     Alienware 17  ...  4.42kg     2868.99     Expensive
780         789    Dell     Alienware 17  ...  4.42kg     3588.80     Expensive
818         827    Dell     Alienware 17  ...  4.36kg     2505.02     Expensive
835         844    Dell     Alienware 15  ...  3.21kg     2774.63     Expensive
841         851    Dell     Alienware 17  ...  4.42kg     3072.89     Expensive
864         875    Dell           XPS 13  ...  1.29kg     2240.00     Expensive
900         912    Dell           XPS 13  ...  1.24kg     2013.10     Expensive
939         953    Dell     Alienware 17  ...  4.36kg     2758.00     Expensive
955         969    Dell     Alienware 17  ...  4.36kg     3154.00     Expensive
968         982    Dell     Alienware 17  ...  4.42kg     3149.00     Expensive
972         986    Dell     Alienware 17  ...  4.42kg     2800.00     Expensive
1054       1068    Dell           XPS 13  ...   1.2kg     2254.00     Expensive
1154       1172    Dell           XPS 15  ...  2.04kg     2250.68     Expensive
1203       1221    Dell           XPS 13  ...   1.2kg     2680.00     Expensive

[39 rows x 15 columns]