In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Syntax 1

In [8]:
df["lunch"]

0          standard
1          standard
2          standard
3      free/reduced
4          standard
           ...
995        standard
996    free/reduced
997    free/reduced
998        standard
999    free/reduced
Name: lunch, Length: 1000, dtype: object

In [9]:
type(df["lunch"])

pandas.core.series.Series

In [10]:
df["lunch"].index

RangeIndex(start=0, stop=1000, step=1)

In [11]:
df["lunch"].head(5)

0        standard
1        standard
2        standard
3    free/reduced
4        standard
Name: lunch, dtype: object

# Syntax 2

In [12]:
df.lunch

0          standard
1          standard
2          standard
3      free/reduced
4          standard
           ...
995        standard
996    free/reduced
997    free/reduced
998        standard
999    free/reduced
Name: lunch, Length: 1000, dtype: object

# Selecting more columns

In [13]:
df[["gender" , "lunch"]]

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
..      ...           ...
995  female      standard
996    male  free/reduced
997  female  free/reduced
998  female      standard
999  female  free/reduced

[1000 rows x 2 columns]

In [14]:
type(df[["gender" , "lunch"]])

pandas.core.frame.DataFrame

In [18]:
df[["gender" , "lunch" , "math score"]]

     gender         lunch  math score
0    female      standard          72
1    female      standard          69
2    female      standard          90
3      male  free/reduced          47
4      male      standard          76
..      ...           ...         ...
995  female      standard          88
996    male  free/reduced          62
997  female  free/reduced          59
998  female      standard          68
999  female  free/reduced          77

[1000 rows x 3 columns]

# Adding new Column

In [20]:
df["lang score"] = 80 # Scalar value
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,lang score
0,female,group B,bachelor's degree,standard,none,72,72,74,80
1,female,group C,some college,standard,completed,69,90,88,80
2,female,group B,master's degree,standard,none,90,95,93,80
3,male,group A,associate's degree,free/reduced,none,47,57,44,80
4,male,group C,some college,standard,none,76,78,75,80
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80
996,male,group C,high school,free/reduced,none,62,55,55,80
997,female,group C,high school,free/reduced,completed,59,71,65,80
998,female,group D,some college,standard,completed,68,78,77,80
999,female,group D,some college,free/reduced,none,77,86,86,80

# With Arrays add new col

In [21]:
import numpy as np

In [25]:
score = np.arange(0 , 1000)

In [26]:
len(score)

1000

In [27]:
df["lang score"] = score

In [28]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,lang score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [31]:
rand_score = np.random.randint(1 , 100 , size=1000)
len(rand_score)

1000

In [35]:
min(rand_score)

np.int32(1)

In [36]:
max(rand_score)

np.int32(99)

In [37]:
df["lang score"] = rand_score
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,lang score
0,female,group B,bachelor's degree,standard,none,72,72,74,81
1,female,group C,some college,standard,completed,69,90,88,73
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,38
4,male,group C,some college,standard,none,76,78,75,27
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,93
996,male,group C,high school,free/reduced,none,62,55,55,4
997,female,group C,high school,free/reduced,completed,59,71,65,49
998,female,group D,some college,standard,completed,68,78,77,2
999,female,group D,some college,free/reduced,none,77,86,86,38

In [39]:
# create a float numbers
np.random.uniform(1 , 100 , size=100)

array([25.86897415, 21.73170079, 64.2527686 , 79.24392381, 99.16887147,
       47.15958538,  3.74164885,  1.79657369, 55.83946357, 82.58640333,
       72.27354155, 41.12151286, 39.22422977, 45.00473271, 89.02405811,
       97.06887041, 18.49896002, 20.68978999, 90.71844904, 47.40313018,
       84.50630698, 72.02639111, 80.89202945, 22.84410223, 49.3488226 ,
       18.680815  , 46.62381826, 91.8161104 , 28.0936306 , 59.89154083,
       15.6233395 , 93.20019103, 63.82659777, 59.72434901, 37.15085142,
       70.57993628, 78.63733381, 97.54514897, 22.43324433,  5.93678926,
       44.38304668, 47.63524879, 82.73821745, 45.48357386, 63.16676644,
       67.64296583, 78.68890916, 23.30085588, 64.90632634, 98.16460024,
       96.58037559, 65.11092789,  5.87028021, 11.38463567, 52.04454635,
       23.02142978, 40.9414258 , 17.93181559, 23.50889579, 98.23154311,
        4.93121618, 42.94856644, 78.96392458, 92.06107257, 88.27220484,
       38.62322145, 16.11531354, 28.82846489, 66.16382608, 70.76369137,
       86.49087546, 55.41287704, 54.14747872, 86.94684979, 80.68475978,
       59.74337158, 26.71444682, 76.50606526, 11.74894693, 30.52633696,
       35.33780139, 98.40080177, 39.45333491,  9.54376832, 24.2870926 ,
       44.72085414, 56.18185452, 35.26631054, 96.13321555, 55.48972638,
       91.70698664, 87.75491367, 32.14624722, 86.41388721,  9.94500295,
       76.19128571, 79.2269437 , 29.15633274, 24.08113774, 15.90585826])

In [43]:
score_1 = np.random.randint(1 , 100 , size=1000)
score_2 = np.random.randint(1 , 100 , size=1000)
series1 = pd.Series(score_1 , index=np.arange(0,1000))
series2 = pd.Series(score_2 , index=np.arange(0,1000))

In [49]:
series1

0       9
1      43
2      37
3       9
4      98
       ..
995     5
996    37
997    55
998    94
999    55
Length: 1000, dtype: int32

In [57]:
df.assign(score1 = score_1 , score2 = score_2)  # Using assign method

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,lang score,score1,score2
0,female,9,group B,bachelor's degree,standard,none,72,72,74,81,9,95
1,female,43,group C,some college,standard,completed,69,90,88,73,43,43
2,female,37,group B,master's degree,standard,none,90,95,93,2,37,2
3,male,9,group A,associate's degree,free/reduced,none,47,57,44,38,9,71
4,male,98,group C,some college,standard,none,76,78,75,27,98,39
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,5,group E,master's degree,standard,completed,88,99,95,93,5,28
996,male,37,group C,high school,free/reduced,none,62,55,55,4,37,86
997,female,55,group C,high school,free/reduced,completed,59,71,65,49,55,6
998,female,94,group D,some college,standard,completed,68,78,77,2,94,98
999,female,55,group D,some college,free/reduced,none,77,86,86,38,55,90

In [60]:
df.insert(1,"test2", series1)

In [61]:
df

,gender,test2,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,lang score
0,female,9,9,group B,bachelor's degree,standard,none,72,72,74,81
1,female,43,43,group C,some college,standard,completed,69,90,88,73
2,female,37,37,group B,master's degree,standard,none,90,95,93,2
3,male,9,9,group A,associate's degree,free/reduced,none,47,57,44,38
4,male,98,98,group C,some college,standard,none,76,78,75,27
...,...,...,...,...,...,...,...,...,...,...,...
995,female,5,5,group E,master's degree,standard,completed,88,99,95,93
996,male,37,37,group C,high school,free/reduced,none,62,55,55,4
997,female,55,55,group C,high school,free/reduced,completed,59,71,65,49
998,female,94,94,group D,some college,standard,completed,68,78,77,2
999,female,55,55,group D,some college,free/reduced,none,77,86,86,38