In [1]:
import pandas as pd
df = pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Sort a DF

In [2]:
df.sort_values(by='math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [3]:
df.sort_values(by='math score' , ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [7]:
df.sort_values(['math score','writing score'] , ascending=False , inplace=True)

In [8]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
451,female,group E,some college,standard,none,100,92,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [9]:
df.sort_values("race/ethnicity" , ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
402,female,group A,some college,free/reduced,none,49,65,55
960,female,group A,some college,standard,none,56,58,64
994,male,group A,high school,standard,none,63,63,62
61,male,group A,some high school,free/reduced,none,39,39,34
586,female,group A,high school,standard,none,55,73,73
...,...,...,...,...,...,...,...,...
915,female,group E,some college,standard,none,68,70,66
751,male,group E,some college,standard,none,68,72,65
592,male,group E,bachelor's degree,standard,none,68,68,64
499,male,group E,some college,standard,none,76,71,72
517,female,group E,some college,standard,completed,66,74,73

# Create Index

In [10]:
import numpy as np
import random

In [32]:
new_idx = np.arange(0,1000)

In [36]:
random.shuffle(new_idx)

In [37]:
df["new_index"] = new_idx
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
458,female,group E,bachelor's degree,standard,none,100,100,100,211
916,male,group E,bachelor's degree,standard,completed,100,100,100,9
962,female,group E,associate's degree,standard,none,100,100,100,300
625,male,group D,some college,standard,completed,100,97,99,547
451,female,group E,some college,standard,none,100,92,97,686
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,285
787,female,group B,some college,standard,none,19,38,32,20
17,female,group B,some high school,free/reduced,none,18,32,28,317
980,female,group B,high school,free/reduced,none,8,24,23,865
59,female,group C,some high school,free/reduced,none,0,17,10,744

In [42]:
df.set_index('new_index' , inplace=True) # set index

In [43]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
211,female,group E,bachelor's degree,standard,none,100,100,100
9,male,group E,bachelor's degree,standard,completed,100,100,100
300,female,group E,associate's degree,standard,none,100,100,100
547,male,group D,some college,standard,completed,100,97,99
686,female,group E,some college,standard,none,100,92,97
...,...,...,...,...,...,...,...,...
285,female,group C,some college,free/reduced,none,22,39,33
20,female,group B,some college,standard,none,19,38,32
317,female,group B,some high school,free/reduced,none,18,32,28
865,female,group B,high school,free/reduced,none,8,24,23
744,female,group C,some high school,free/reduced,none,0,17,10

In [48]:
df.sort_index(inplace=True)   # Sort index

In [49]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,female,group C,associate's degree,standard,none,39,64,57
1,female,group C,master's degree,standard,none,73,78,74
2,male,group D,some college,standard,completed,63,55,63
3,female,group C,high school,standard,none,66,71,76
4,female,group E,high school,standard,completed,59,63,75
...,...,...,...,...,...,...,...,...
995,male,group C,high school,standard,none,62,67,58
996,female,group B,high school,free/reduced,none,38,60,50
997,female,group B,some high school,standard,completed,32,51,44
998,male,group C,high school,standard,none,70,74,71
999,male,group E,associate's degree,free/reduced,completed,100,100,93